# $ docker-compose run rms-client
version: "3"
services:
  rms-server:
    image: extactmame/rms-server:latest
    container_name: "rms-server"
    ports:
      - "7011:7011"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/health"]
      start_period: 5s
      retries: 3
      timeout: 5s
      interval: 60s
  rms-client:
    image: extactmame/rms-client:latest
    container_name: "rms-client"
    depends_on:
      - rms-server
    environment:
      - SERVER_URL=http://rms-server:7001
    tty: true
    stdin_open: true
    command: ["./docker-wait-for-server.sh", "java", "-jar", "rms-client-ui-console.jar"]
