version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rmsServiceApp
hooks:

  BeforeInstall:
    - location: scripts/delete_modules.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
